### ISSUE TITLE
windows下docker uwsgi.sock出错

### ISSUE THREAD

**Issue by dusunboy** [magic-joker/Docker#1]
unix:///sock/uwsgi.sock failed (2: No such file or directory)
找不到这个文件，为啥呀

**Comment by magic-joker** [comment]
你使用的是哪个？ Stable_version?

**Comment by dusunboy** [comment]
对的， 日志是报这个错，目前我是把nginx也放在flask里，这样sock不需要共享目录了。

**Comment by magic-joker** [comment]
windows下我没测试过,我一般都是linux用
